chore(docs): Update README to Include Async Ex
moxystudio/next-router-scroll pull request #7
Opened 2021-04-27 17:35 UTC by therynamo

Most complex UIs will utilize, in one form or another, async rendering. It is helpful to see how this library may be useful in approaching that problem.

closes #6

2021-04-27 19:48 UTC, satazor requested changes
Just some minor changes based on the code style of the rest of the README.

2021-04-27 19:48 UTC, satazor commented on README.md
> +  );
```suggestion
    const divRef = useCallback((node) => {
        if (node) {
            updateScroll();
        }
    }, [updateScroll]
);
```

2021-04-27 19:48 UTC, satazor commented on README.md
> +}
```suggestion

    return someCondition ? <div ref={ divRef }>hi</div> : null;
};
```

2021-04-28 17:59 UTC, therynamo commented
Perfect! Updated @satazor

2021-04-30 00:56 UTC, merged